#!/usr/bin/env python
import globalSetting
import os
import getCmdPath
############################################
#     PLEASE DO NOT EDIT THIS FILE         #
############################################

# This file will create the needed dir
# The format is
#   ~/AstroSoft
#
__author__ = "Guo Shaoguang<sgguo@shao.ac.cn>"
__version__ = 1.0
__date__ = "2015-08-18"


def createDir():
    all_dir = []
    dir_len = []

    # Get all the dirs should be create
    for tmp in vars(globalSetting).items():
        if globalSetting.MARK in tmp[0]:
            all_dir.append(tmp[1])
            dir_len.append(len(tmp[1]))
            #print 'the length of %s is %d' % (tmp[1],len(tmp[1]))
    print all_dir
    #print dir_len

    # Ready to create
    for tmp in all_dir:
        if os.path.exists(tmp):
            pass
        else:
            print 'Now create dir ( %s )' % tmp
            # remember add the -p option to create intermediate directories
            os.system(getCmdPath.getCmdPath('mkdir')+ ' '+' -p'+ ' ' +tmp)
            #print (getCmdPath.getCmdPath('mkdir')+ ' ' +tmp)


if __name__ == '__main__':
    createDir()
