#!/usr/bin/env python

############################################
#     PLEASE DO NOT EDIT THIS FILE         #
############################################

import sep
import supportOS
import terminalColor

# This file will print support os and related software
__author__ = "Guo Shaoguang<sgguo@shao.ac.cn>"
__version__ = 1.0
__date__ = "2015-08-18"
def history():
    print '\n'*2
    #print 'The script will install some Astronomical Software automaticlly'
    #print terminalColor.GREEN
    print terminalColor.BLINK_GREEN_TEXT_WHITE_BACKGROUND
    print '>>> Now this script will support the following OS and software'
    print terminalColor.NONE
    sep.sep()
    #print 'Support OS        \t| Software Version\t|'
    for tmp in range(len(supportOS.support_os)):
        for tmpA in supportOS.support_os[tmp]:
            print tmpA ,
    #print supportOS.support_os + 'Ubuntu 14.04 64bit\t|                 \t|'
    sep.sep()
