#!/usr/bin/env python
#import os
import global_setting
############################################
#     PLEASE DO NOT EDIT THIS FILE         #
############################################

# This file will create the needed dir
# The format is
#   ~/AstroSoft
#
__author__ = "Guo Shaoguang<sgguo@shao.ac.cn>"
__version__ = 1.0
__date__ = "2015-08-19"

def preUbuntu():
    print '#'*60
    print 'First Please make sure you have installed the following depend softwares.'
    print '-'*60
    print 'sudo apt-get install '
    for tmp in global_setting.PreUbuntu_software.split():
        print '                   \t -> %s' % (tmp)
    #print global_setting.PreUbuntu_software[1]
    print 'sudo pip install '
    for tmp in global_setting.PrePip_software.split():
        print '                \t-> %s' % (tmp)
    print '-'*60
    pass

if __name__ == '__main__':
    preUbuntu()
