#!/usr/bin/env python

############################################
#     PLEASE DO NOT EDIT THIS FILE         #
############################################

import support_os
import terminalColor

# This file will print support os and related software
__author__ = "Guo Shaoguang<sgguo@shao.ac.cn>"
__version__ = 1.0
__date__ = "2015-08-18"
def history():
    print '\n'*2
    #print 'The script will install some Astronomical Software automaticlly'
    #print terminalColor.RED
    print terminalColor.BLINK_GREEN_TEXT_WHITE_BACKGROUND
    print '>>> Now this script will support the following OS and software',
    print terminalColor.NONE
    print support_os.show_support_os()

if __name__ == '__main__':
    history()
